eval "$(oh-my-posh init bash --config ~/scoop/apps/oh-my-posh/current/themes/samip.omp.json)"

alias mongod="/c/Program\ files/MongoDB/Server/4.2/bin/mongod.exe"
alias mongo="/c/Program\ Files/MongoDB/Server/4.2/bin/mongo.exe"
alias desk="cd ~/Desktop"
alias ddrive="cd /D"
alias sbox="cd ~/Desktop/sandbox"
alias vreact="cd ~/Desktop/sandbox/vite-react"
alias vreacts="cd ~/Desktop/sandbox/vite-react-ts"
alias root="cd ~"
alias exp="cd ~/Desktop/experiments"
alias icode="code-insiders"
alias pad="notepad"
alias play="cd ~/Desktop/playground/code"
alias dev="npm run dev"
alias imgcomp="node /D/Web\ Dev\ Projects/img-ops/app.js"
alias playreact="code ~/Desktop/sandbox/next-tail-ts"
alias ..="cd .."
alias ...="cd ../.."
alias cyp="npx cypress run --spec"
alias tree="tree -I '.git|node_modules|bower_components|.DS_Store'"
alias dkrinfo="(docker container ls -a | bat) && (docker image ls | bat) && (docker volume ls | bat) && (docker network ls | bat)"
alias valias="nvim ~/.dotfiles/.bash_profile"
